name: Deploy to EKS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Node.js App Image
        run: |
          docker build -t app ./app
          docker tag app:latest ${{ secrets.ECR_REPO_APP }}:latest
          docker push ${{ secrets.ECR_REPO_APP }}:latest

      - name: Build and Push Nginx Image
        run: |
          docker build -t nginx ./nginx
          docker tag nginx:latest ${{ secrets.ECR_REPO_NGINX }}:latest
          docker push ${{ secrets.ECR_REPO_NGINX }}:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-cluster

      - name: Deploy to EKS
        run: | 
          kubectl apply -f ./k8s/

